### ISSUE TITLE
Keyboard shortcuts on Firefox/Windows 10 do not work

### ISSUE THREAD

**Issue by menakas** [Automattic/happychat-service#119]
None of the keyboard shortcuts for Happychat work on my Firefox browser on Windows 10.

When I open [http://happychat.io](http://happychat.io) on my Firefox browser, I am unable to use the keyboard shortcuts.

**Comment by unDemian** [comment]
This repo has been closed. Issues related to Happychat should be reported to https://github.com/Automattic/happychat/issues
