### ISSUE TITLE
'online' status no longer used

### ISSUE THREAD

**Issue by mjangda** [Automattic/happychat-service#59]
On an operator `status` request, we do this:

```
if ( status === 'online' ) {
            debug( 'joining room', 'online' )
            socket.join( 'online', updateStatus )
        } else {
            socket.leave( 'online', updateStatus )
        }
```

The status `online` should be `available`, although, I'm not sure if we use the room at all so maybe this block can be removed and `updateStatus` can just be triggered.

**Comment by beaucollins** [comment]
The room used to be used during chat assignment. Only operators in that room would receive an assignment request.

Now that we're handling more of that in the service itself by proactively tracking and storing operator status we can remove this.
